using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace NodeRunner.Ui.Tests;

/// <summary>
/// Builds <c>project/locale/messages.pot</c>, the template translators start from (#778). Godot's
/// own generator runs only from the editor and reads scenes and GDScript, so it misses our
/// components' text properties, App <see cref="App.ViewModels.UiText"/> and text set in C#.
/// </summary>
internal static partial class TranslationTemplate
{
    public const string Path = "project/locale/messages.pot";

    /// <summary>One message to translate: <see cref="Plural"/> is set for counted text.</summary>
    public sealed record Entry(string? Context, string Id, string? Plural);

    /// <summary>
    /// Every message with the files it comes from, and the places whose text can't be read
    /// without running the game.
    /// </summary>
    public sealed record Extraction(IReadOnlyDictionary<Entry, SortedSet<string>> Entries, IReadOnlyList<string> Problems);

    private static readonly Lazy<Extraction> _current = new(() => Extract(RepositorySources(), SceneFiles()));

    public static Extraction Current => _current.Value;

    public static Extraction Extract(IReadOnlyList<CSharpSources.Source> code, IEnumerable<(string Path, string Text)> scenes)
    {
        var entries = new Dictionary<Entry, SortedSet<string>>();
        var problems = new List<string>();
        var codeText = new CodeText(code, problems);
        foreach (var (entry, source) in codeText.Messages()
            .Concat(scenes.SelectMany(scene => SceneText(scene.Path, scene.Text.ReplaceLineEndings("\n"), codeText))))
        {
            if (entry.Id.Any(char.IsLetter))
            {
                entries.TryAdd(entry, []);
                entries[entry].Add(source);
            }
        }

        // gettext keys a message by context and msgid, so one id can't be both plain and counted.
        problems.AddRange(entries.Keys
            .GroupBy(entry => (entry.Context, entry.Id))
            .Where(group => group.Count() > 1)
            .Select(group => $"\"{group.Key.Id}\" is used both {string.Join(" and ", group.Select(entry => entry.Plural is null ? "alone" : $"with plural \"{entry.Plural}\""))}"));
        return new Extraction(entries, problems);
    }

    public static string Render(Extraction extraction)
    {
        var pot = new StringBuilder();
        pot.Append("# Node Runner UI text. Generated by TranslationTemplateTests; do not edit (docs/LOCALIZATION.md).\n");
        pot.Append("msgid \"\"\n");
        pot.Append("msgstr \"\"\n");
        pot.Append("\"Content-Type: text/plain; charset=UTF-8\\n\"\n");
        pot.Append("\"Content-Transfer-Encoding: 8bit\\n\"\n");
        foreach (var (entry, sources) in extraction.Entries
            .OrderBy(pair => pair.Key.Context ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(pair => pair.Key.Id, StringComparer.Ordinal)
            .ThenBy(pair => pair.Key.Plural ?? string.Empty, StringComparer.Ordinal))
        {
            pot.Append('\n');
            foreach (var source in sources)
            {
                pot.Append("#: ").Append(source).Append('\n');
            }

            if (entry.Context is not null)
            {
                pot.Append("msgctxt ").Append(Quote(entry.Context)).Append('\n');
            }

            pot.Append("msgid ").Append(Quote(entry.Id)).Append('\n');
            if (entry.Plural is null)
            {
                pot.Append("msgstr \"\"\n");
            }
            else
            {
                pot.Append("msgid_plural ").Append(Quote(entry.Plural)).Append('\n');
                pot.Append("msgstr[0] \"\"\n");
                pot.Append("msgstr[1] \"\"\n");
            }
        }

        return pot.ToString();
    }

    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\t", "\\t") + "\"";

    /// <summary>The pure libs and <c>project/src</c>, so text can be followed across them.</summary>
    private static IReadOnlyList<CSharpSources.Source> RepositorySources()
    {
        var root = SceneNodes.FindRepositoryRoot();
        return new[] { "libs", "project/src" }
            .Select(folder => System.IO.Path.Combine(root, folder))
            .SelectMany(folder => Directory.EnumerateFiles(folder, "*.cs", SearchOption.AllDirectories)
                .Where(path => !System.IO.Path.GetRelativePath(folder, path).Split('/', '\\').Any(part => part is "obj" or "bin")))
            .Order(StringComparer.Ordinal)
            .Select(path => new CSharpSources.Source(
                System.IO.Path.GetRelativePath(root, path).Replace('\\', '/'),
                CSharpSyntaxTree.ParseText(File.ReadAllText(path).ReplaceLineEndings("\n"), path: path)))
            .ToList();
    }

    private static IEnumerable<(string Path, string Text)> SceneFiles()
    {
        var root = SceneNodes.FindRepositoryRoot();
        return Directory.EnumerateFiles(System.IO.Path.Combine(root, "project", "scenes"), "*.tscn", SearchOption.AllDirectories)
            .Order(StringComparer.Ordinal)
            .Select(path => (System.IO.Path.GetRelativePath(root, path).Replace('\\', '/'), File.ReadAllText(path)));
    }

    // ---- Scenes ----

    /// <summary>
    /// Godot's translated node properties, plus our components' exported text, which Godot's
    /// generator doesn't know about. <c>TextValue</c> is what the player typed into a text field.
    /// </summary>
    private static readonly HashSet<string> _nativeSceneText = ["text", "tooltip_text", "placeholder_text", "title"];

    private static IEnumerable<(Entry Entry, string Source)> SceneText(string path, string text, CodeText code)
    {
        var nodes = SceneNodes.Parse(path, text).ToList();
        if (nodes.FirstOrDefault(node => node.IsRoot)?.Script is { } rootScript && code.IsGallery(rootScript.Replace("res://", "project/", StringComparison.Ordinal)))
        {
            yield break;
        }

        var modes = new Dictionary<string, string>();
        var contexts = new Dictionary<string, string?>();
        foreach (var node in nodes)
        {
            var nodePath = node.IsRoot ? "." : node.Parent == "." ? node.Name : $"{node.Parent}/{node.Name}";
            var properties = Properties(node.Node.Body);
            var mode = properties.GetValueOrDefault("auto_translate_mode") ?? "0";
            modes[nodePath] = mode == "0" && node.Parent is { } parent ? modes.GetValueOrDefault(parent, "0") : mode;
            contexts[nodePath] = properties.GetValueOrDefault("translation_context") is { } context ? GodotString(context) : null;
            if (modes[nodePath] == "2")
            {
                continue;
            }

            foreach (var (key, value) in properties)
            {
                if (code.IsSceneText(key))
                {
                    foreach (var message in GodotStrings(value))
                    {
                        yield return (new Entry(Blank(contexts[nodePath]), message, null), path);
                    }
                }
            }

            // A switch's segments are resources; it translates them with its own context.
            foreach (Match reference in SubResourceRef().Matches(node.Node.Body))
            {
                foreach (var message in SubResourceText(text, reference.Groups["id"].Value, code))
                {
                    yield return (new Entry(Blank(contexts[nodePath]), message, null), path);
                }
            }
        }
    }

    private static IEnumerable<string> SubResourceText(string scene, string id, CodeText code)
    {
        var block = SubResourceBlock().Matches(scene).FirstOrDefault(match => match.Groups["id"].Value == id);
        return block is null
            ? []
            : Properties(block.Value).Where(property => code.IsSceneText(property.Key)).SelectMany(property => GodotStrings(property.Value));
    }

    private static string? Blank(string? context) => string.IsNullOrEmpty(context) ? null : context;

    /// <summary>A block's <c>key = value</c> lines; a string value may span lines.</summary>
    private static Dictionary<string, string> Properties(string block)
    {
        var properties = new Dictionary<string, string>();
        foreach (Match match in SceneProperty().Matches(block))
        {
            properties[match.Groups["key"].Value] = match.Groups["value"].Value;
        }

        return properties;
    }

    private static IEnumerable<string> GodotStrings(string value) =>
        GodotStringLiteral().Matches(value).Select(match => Unescape(match.Groups["body"].Value));

    private static string GodotString(string value) => GodotStrings(value).FirstOrDefault() ?? string.Empty;

    private static string Unescape(string body) =>
        Regex.Replace(body, @"\\(.)", match => match.Groups[1].Value switch
        {
            "n" => "\n",
            "t" => "\t",
            var other => other,
        });

    [GeneratedRegex("""(?m)^(?<key>[A-Za-z_][A-Za-z0-9_/]*) = (?<value>(?:&?"(?:[^"\\]|\\.)*"|[^\n])*)""")]
    private static partial Regex SceneProperty();

    [GeneratedRegex(@"&?""(?<body>(?:[^""\\]|\\.)*)""")]
    private static partial Regex GodotStringLiteral();

    [GeneratedRegex("""SubResource\("(?<id>[^"]+)"\)""")]
    private static partial Regex SubResourceRef();

    [GeneratedRegex("""(?ms)^\[sub_resource [^\]]*id="(?<id>[^"]+)"\]\n.*?(?=^\[|\z)""")]
    private static partial Regex SubResourceBlock();

    // ---- C# ----

    /// <summary>
    /// Follows constant text in C# to where it is shown: a translated Godot text property, one of
    /// our components' or popups' text properties, or a <c>UiText</c> factory. It follows
    /// assignments, arguments, returns, locals and <c>?:</c>/<c>??</c>/switch branches.
    /// </summary>
    private sealed class CodeText
    {
        private static readonly HashSet<string> _godotText = ["Text", "TooltipText", "PlaceholderText", "Title"];
        private static readonly HashSet<string> _popupContracts = ["UiDialogSpec", "UiNotificationSpec", "UiDialogResult", "UiPickerOption"];

        private readonly IReadOnlyList<CSharpSources.Source> _sources;
        private readonly List<string> _problems;
        private readonly CSharpCompilation _compilation;
        private readonly HashSet<string> _componentText;
        private readonly HashSet<string> _galleryScripts;

        // Every value that flows into a symbol: what is assigned to it, passed as it, or returned by it.
        private readonly Dictionary<ISymbol, List<Seed>> _feeds = new(SymbolEqualityComparer.Default);

        public CodeText(IReadOnlyList<CSharpSources.Source> sources, List<string> problems)
        {
            _sources = sources;
            _problems = problems;
            _compilation = CSharpSources.CompileWithLibs(sources);
            _componentText = _compilation.GetSymbolsWithName(_ => true, SymbolFilter.Member)
                .OfType<IPropertySymbol>()
                .Where(property => property.GetAttributes().Any(attribute => attribute.AttributeClass?.Name == "ExportAttribute") && IsSinkProperty(property))
                .Select(property => property.Name)
                .ToHashSet(StringComparer.Ordinal);
            var gallery = _compilation.GetTypeByMetadataName("NodeRunner.Ui.Screens.GalleryScreen");
            _galleryScripts = sources
                .Where(source => source.Tree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>()
                    .Any(type => CSharpSources.DerivesFrom(_compilation.GetSemanticModel(source.Tree).GetDeclaredSymbol(type), gallery)))
                .Select(source => source.Path)
                .ToHashSet(StringComparer.Ordinal);
        }

        /// <summary>
        /// Godot's translated node properties, or one of our components' exported text properties,
        /// by its saved name.
        /// </summary>
        public bool IsSceneText(string key) => _nativeSceneText.Contains(key) || _componentText.Contains(key);

        /// <summary>A gallery screen's script, by its path from the repository root.</summary>
        public bool IsGallery(string path) => _galleryScripts.Contains(path);

        /// <summary>A property whose text the player sees, translated by Godot.</summary>
        public static bool IsSinkProperty(IPropertySymbol property)
        {
            if (!IsText(property.Type) || property.Name == "TextValue")
            {
                return false;
            }

            var type = property.ContainingType;
            if (type.ContainingNamespace?.ToDisplayString() == "Godot")
            {
                return _godotText.Contains(property.Name);
            }

            return type.ContainingNamespace?.ToDisplayString() == "NodeRunner.Ui.Lib"
                && (_popupContracts.Contains(type.Name) || Derives(type, "Control") || Derives(type, "Resource"));
        }

        public IEnumerable<(Entry Entry, string Source)> Messages()
        {
            var seeds = new List<Seed>();
            var messages = new List<(Entry, string)>();
            foreach (var source in _sources)
            {
                var model = _compilation.GetSemanticModel(source.Tree);
                foreach (var node in source.Tree.GetRoot().DescendantNodes())
                {
                    Index(node, model, source, seeds, messages);
                }
            }

            return messages.Concat(Follow(seeds)).Where(message => !IsGallery(message.Item2));
        }

        private void Index(SyntaxNode node, SemanticModel model, CSharpSources.Source source, List<Seed> seeds, List<(Entry, string)> messages)
        {
            switch (node)
            {
                case InvocationExpressionSyntax call when UiTextFactory(call, model) is { } factory:
                    messages.AddRange(UiTextMessages(call, factory, model, source, seeds));
                    break;
                case AssignmentExpressionSyntax assignment when CSharpSources.Symbol(model, assignment.Left) is { } target:
                    Feed(target, assignment.Right, source, seeds);
                    break;
                case VariableDeclaratorSyntax { Initializer.Value: var value } declarator when model.GetDeclaredSymbol(declarator) is { } variable:
                    Feed(variable, value, source, seeds);
                    break;
                case PropertyDeclarationSyntax property when model.GetDeclaredSymbol(property) is { } declared:
                    foreach (var value in Returns(property.ExpressionBody, property.AccessorList?.Accessors.FirstOrDefault(accessor => accessor.Keyword.IsKind(SyntaxKind.GetKeyword))).Append(property.Initializer?.Value).OfType<ExpressionSyntax>())
                    {
                        Feed(declared, value, source, seeds);
                    }

                    break;
                case MethodDeclarationSyntax method when model.GetDeclaredSymbol(method) is { } declared && IsText(declared.ReturnType):
                    foreach (var value in Returns(method.ExpressionBody, method.Body))
                    {
                        Feed(declared, value, source, seeds);
                    }

                    break;
                case ParameterSyntax { Default.Value: var value } parameter when model.GetDeclaredSymbol(parameter) is { } declared:
                    Feed(declared, value, source, seeds);
                    break;
                case ArgumentSyntax argument when model.GetOperation(argument) is IArgumentOperation { Parameter: { } parameter }:
                    Feed(parameter, argument.Expression, source, seeds);
                    break;
                case ForEachStatementSyntax loop when model.GetDeclaredSymbol(loop) is { } element:
                    Feed(element, loop.Expression, source, seeds);
                    break;
            }
        }

        private void Feed(ISymbol target, ExpressionSyntax value, CSharpSources.Source source, List<Seed> seeds)
        {
            if (target is IPropertySymbol property && IsSinkProperty(property))
            {
                seeds.Add(new Seed(value, source.Path, MustBeKnown: false));
                return;
            }

            if (!_feeds.TryGetValue(target.OriginalDefinition, out var feeds))
            {
                _feeds[target.OriginalDefinition] = feeds = [];
            }

            feeds.Add(new Seed(value, source.Path, MustBeKnown: false));

            // A record's positional parameter is its property.
            if (target is IParameterSymbol { ContainingSymbol: IMethodSymbol { MethodKind: MethodKind.Constructor } constructor } parameter
                && constructor.ContainingType.IsRecord
                && constructor.ContainingType.GetMembers(parameter.Name).OfType<IPropertySymbol>().FirstOrDefault() is { } positional)
            {
                Feed(positional, value, source, seeds);
            }
        }

        // The constant text reachable from shown values, through the symbols that carry it. A seed
        // that must be known, a UiText's message, reports every value it can't trace to text.
        private IEnumerable<(Entry, string)> Follow(List<Seed> seeds)
        {
            var visited = new HashSet<(ISymbol, bool)>();
            var pending = new Queue<Seed>(seeds);
            while (pending.TryDequeue(out var item))
            {
                if (IsGallery(item.Source))
                {
                    continue;
                }

                var model = _compilation.GetSemanticModel(item.Value.SyntaxTree);
                foreach (var leaf in Leaves(item.Value, model))
                {
                    switch (leaf)
                    {
                        case string text:
                            yield return (new Entry(null, text, null), item.Source);
                            break;
                        case ISymbol symbol when _feeds.TryGetValue(symbol.OriginalDefinition, out var feeds):
                            if (visited.Add((symbol.OriginalDefinition, item.MustBeKnown)))
                            {
                                foreach (var feed in feeds)
                                {
                                    pending.Enqueue(feed with { MustBeKnown = item.MustBeKnown });
                                }
                            }

                            break;
                        case var unknown when item.MustBeKnown:
                            var expression = unknown as ExpressionSyntax ?? item.Value;
                            _problems.Add(_sources.Single(source => source.Tree == expression.SyntaxTree).Describe(expression)
                                + " — a UiText needs literal text, or text that can be traced to one");
                            break;
                    }
                }
            }
        }

        // The constants and symbols an expression's value can come from; any other expression is
        // returned as itself, as text that can't be traced.
        private static IEnumerable<object> Leaves(ExpressionSyntax value, SemanticModel model)
        {
            if (model.GetConstantValue(value) is { HasValue: true, Value: string constant })
            {
                return [constant];
            }

            return value switch
            {
                ParenthesizedExpressionSyntax inner => Leaves(inner.Expression, model),
                CastExpressionSyntax cast => Leaves(cast.Expression, model),
                ConditionalExpressionSyntax choice => Leaves(choice.WhenTrue, model).Concat(Leaves(choice.WhenFalse, model)),
                BinaryExpressionSyntax binary when binary.IsKind(SyntaxKind.CoalesceExpression) => Leaves(binary.Left, model).Concat(Leaves(binary.Right, model)),
                SwitchExpressionSyntax choice => choice.Arms.SelectMany(arm => Leaves(arm.Expression, model)),
                CollectionExpressionSyntax collection => collection.Elements.OfType<ExpressionElementSyntax>().SelectMany(element => Leaves(element.Expression, model)),
                ImplicitArrayCreationExpressionSyntax array => array.Initializer.Expressions.SelectMany(element => Leaves(element, model)),
                ArrayCreationExpressionSyntax { Initializer: { } initializer } => initializer.Expressions.SelectMany(element => Leaves(element, model)),
                IdentifierNameSyntax or MemberAccessExpressionSyntax or InvocationExpressionSyntax or ElementAccessExpressionSyntax
                    when CSharpSources.Symbol(model, value is ElementAccessExpressionSyntax element ? element.Expression : value) is { } symbol
                    && symbol is IPropertySymbol or IFieldSymbol or ILocalSymbol or IParameterSymbol or IMethodSymbol => [symbol],
                _ => [value],
            };
        }

        private static IEnumerable<ExpressionSyntax> Returns(ArrowExpressionClauseSyntax? arrow, SyntaxNode? body) =>
            arrow is not null
                ? [arrow.Expression]
                : body?.DescendantNodes(node => node is not (LocalFunctionStatementSyntax or AnonymousFunctionExpressionSyntax))
                    .OfType<ReturnStatementSyntax>()
                    .Select(statement => statement.Expression)
                    .OfType<ExpressionSyntax>() ?? [];

        private static IMethodSymbol? UiTextFactory(InvocationExpressionSyntax call, SemanticModel model) =>
            CSharpSources.Symbol(model, call) is IMethodSymbol { Name: "Plain" or "Format" or "Counted", IsStatic: true, ContainingType: { Name: "UiText" } type } method
            && type.ContainingNamespace.ToDisplayString() == "NodeRunner.App.ViewModels"
                ? method
                : null;

        private IEnumerable<(Entry, string)> UiTextMessages(
            InvocationExpressionSyntax call, IMethodSymbol factory, SemanticModel model, CSharpSources.Source source, List<Seed> seeds)
        {
            if (source.Path.EndsWith("/UiText.cs", StringComparison.Ordinal) || call.ArgumentList.Arguments.Count == 0)
            {
                yield break;
            }

            var message = call.ArgumentList.Arguments[0].Expression;
            var plural = factory.Name == "Counted" ? call.ArgumentList.Arguments[1].Expression : null;
            var context = call.Parent is MemberAccessExpressionSyntax { Name.Identifier.Text: "InContext", Parent: InvocationExpressionSyntax inContext }
                ? inContext.ArgumentList.Arguments[0].Expression
                : null;
            var id = Constant(message, model);
            var pluralText = plural is null ? null : Constant(plural, model);
            var contextText = context is null ? null : Constant(context, model);
            if (id is not null && (plural is null || pluralText is not null) && (context is null || contextText is not null))
            {
                yield return (new Entry(contextText, id, pluralText), source.Path);
            }
            else if (plural is null && context is null)
            {
                // Plain text from elsewhere, such as a data table: follow it to its literal.
                seeds.Add(new Seed(message, source.Path, MustBeKnown: true));
            }
            else
            {
                _problems.Add(source.Describe(call) + " — counted text and a context need literal text");
            }
        }

        private static string? Constant(ExpressionSyntax expression, SemanticModel model) =>
            model.GetConstantValue(expression) is { HasValue: true, Value: string text } ? text : null;

        private static bool IsText(ITypeSymbol type) =>
            type.SpecialType == SpecialType.System_String
            || type is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_String }
            || type is INamedTypeSymbol { Name: "IEnumerable" or "IReadOnlyList", TypeArguments: [{ SpecialType: SpecialType.System_String }] };

        /// <summary>A value whose text is followed, and whether it must all be traced to literals.</summary>
        private sealed record Seed(ExpressionSyntax Value, string Source, bool MustBeKnown);

        private static bool Derives(ITypeSymbol? type, string godotType)
        {
            for (var current = type; current is not null; current = current.BaseType)
            {
                if (current.Name == godotType && current.ContainingNamespace?.ToDisplayString() == "Godot")
                {
                    return true;
                }
            }

            return false;
        }
    }
}
