using Godot;
using NodeRunner.Ui.Lib;

namespace NodeRunner.Ui.Tests;

public sealed class UiThemeExpanderTests
{
    [Fact]
    public void TokenIdentifiers_MapToStableThemeNames()
    {
        var expectedColors = new[]
        {
            "transparent", "background", "panel", "panel_raised", "line", "line_strong",
            "edge", "ink", "muted", "accent", "halo", "on_accent", "danger",
            "scrim", "output",
        };
        Enum.GetValues<UiTokens.Color>().Select(UiTokens.Name).ShouldBe(expectedColors);

        Enum.GetValues<UiTokens.Flag>()
            .Select(UiTokens.Name)
            .ShouldBe(new[] { "effects_enabled" });
        Enum.GetValues<UiTokens.Alpha>()
            .Select(UiTokens.Name)
            .ShouldBe(new[] { "alpha_soft" });
        Enum.GetValues<UiTokens.Typography>()
            .Select(UiTokens.Variation)
            .ShouldBe(new[]
            {
                "UiTitle", "UiHeading", "UiSubheading", "UiStage", "UiBody", "UiBodyStrong",
                "UiSmall", "UiSmallStrong", "UiLabel", "UiNote", "UiNoteStrong", "UiCaption",
                "UiOverline", "UiReadoutLarge", "UiReadout", "UiReadoutMedium", "UiReadoutSmall",
            });
    }

    public static TheoryData<UiTokenType> ThemeFiles => new(Enum.GetValues<UiTokenType>());

    [Theory]
    [MemberData(nameof(ThemeFiles))]
    public void ThemeFile_AuthorsEveryPaletteTokenButNoGlowVariants(UiTokenType type)
    {
        var theme = ThemeFile.For(type);

        foreach (var color in Enum.GetValues<UiTokens.Color>())
        {
            theme.Has(UiThemes.TokenType, "colors", UiTokens.Name(color)).ShouldBeTrue($"{type} lacks {color}");
        }
        foreach (var constant in UiThemeExpander.AuthoredConstants)
        {
            theme.Has(UiThemes.TokenType, "constants", constant).ShouldBeTrue($"{type} lacks {constant}");
        }
        theme.Color(UiTokens.Color.Transparent).ShouldBe(Colors.Transparent);

        // Alpha-only variants of a palette color are not colors of their own: glow comes from
        // UiGlow and translucent fills from Color.WithAlpha(UiTokens.Alpha).
        theme.ItemKeys.Where(key => key.StartsWith($"{UiThemes.TokenType}/colors/", StringComparison.Ordinal))
            .ShouldBe(Enum.GetValues<UiTokens.Color>().Select(color => $"{UiThemes.TokenType}/colors/{UiTokens.Name(color)}"), ignoreOrder: true);
    }

    // Derived items are generated by tools/ExpandThemes.tscn. These fail when a palette
    // color in a theme file was edited without regenerating the file.
    [Theory]
    [MemberData(nameof(ThemeFiles))]
    public void ThemeFile_DerivedColorsMatchItsPalette(UiTokenType type)
    {
        var theme = ThemeFile.For(type);

        foreach (var (variation, baseType) in UiThemeExpander.DerivedBaseTypes)
        {
            theme.BaseType(variation).ShouldBe(baseType, variation);
        }
        foreach (var item in UiThemeExpander.DerivedColors)
        {
            theme.Color(item.Type, item.Name)
                .ShouldBe(theme.Color(item.Token).ScaleAlpha(item.AlphaScale), $"{item.Type}/{item.Name}");
        }
        theme.ItemKeys.Where(key => key.Contains("/colors/", StringComparison.Ordinal)
                && !key.StartsWith($"{UiThemes.TokenType}/", StringComparison.Ordinal))
            .ShouldBe(UiThemeExpander.DerivedColors.Select(item => $"{item.Type}/colors/{item.Name}"), ignoreOrder: true);
    }

    // UiButton's native text is storage only; its internal UiLabel renders the caption. Every
    // palette must hide it, because Godot checks a theme's base Button colors before falling
    // back to the project theme's variation.
    [Theory]
    [MemberData(nameof(ThemeFiles))]
    public void ThemeFile_HidesUiButtonNativeText(UiTokenType type)
    {
        var theme = ThemeFile.For(type);

        theme.BaseType(UiThemeExpander.ButtonVariationName).ShouldBe("Button");
        foreach (var state in new[] { "font_color", "font_focus_color", "font_hover_color", "font_pressed_color", "font_hover_pressed_color", "font_disabled_color", "font_outline_color" })
        {
            theme.Color(UiThemeExpander.ButtonVariationName, state).A.ShouldBe(0f, state);
        }
    }

    [Fact]
    public void ProjectTheme_AuthorsEveryTypographyVariation()
    {
        var theme = ThemeFile.For(UiTokenType.Neon);

        foreach (var typography in Enum.GetValues<UiTokens.Typography>())
        {
            var variation = UiTokens.Variation(typography);
            theme.BaseType(variation).ShouldBe("Label");
            theme.Has(variation, "fonts", "font").ShouldBeTrue(variation);
            theme.Has(variation, "font_sizes", "font_size").ShouldBeTrue(variation);
            theme.Constant(variation, "line_spacing").ShouldBe(0);
        }
        theme.Constant("Label", "line_spacing").ShouldBe(0);
    }

    // Palette-independent items live once, in the project theme; Paper inherits them
    // through Godot's project-theme fallback, so a copy here would be a second source.
    [Fact]
    public void PaperTheme_AuthorsOnlyPaletteDerivedItems()
    {
        var theme = ThemeFile.For(UiTokenType.Paper);

        theme.ItemKeys.Where(key => !key.Contains("/colors/", StringComparison.Ordinal)
                && !key.EndsWith("/base_type", StringComparison.Ordinal)
                && !key.StartsWith($"{UiThemes.TokenType}/constants/", StringComparison.Ordinal))
            .ShouldBeEmpty();
    }

    [Fact]
    public void ProjectTheme_IsNeonSoEditorPreviewsAreThemed()
    {
        var settings = File.ReadAllText(Path.Combine(ThemeFile.ProjectRoot, "project.godot"));

        settings.ShouldContain($"theme/custom=\"{UiThemes.PathFor(UiTokenType.Neon)}\"");
    }

    [Fact]
    public void Dimensions_MatchTheReferenceTokenScale()
    {
        UiSize.Space.S1.ShouldBe(4);
        UiSize.Space.S2.ShouldBe(8);
        UiSize.Space.S3.ShouldBe(12);
        UiSize.Space.S4.ShouldBe(16);
        UiSize.Space.S5.ShouldBe(24);

        UiSize.Control.ExtraSmall.ShouldBe(24);
        UiSize.Control.Small.ShouldBe(32);
        UiSize.Control.Default.ShouldBe(40);
        UiSize.Control.Touch.ShouldBe(48);

        UiSize.Icon.Small.ShouldBe(12);
        UiSize.Icon.Default.ShouldBe(16);
        UiSize.Icon.Large.ShouldBe(20);
        UiSize.Icon.ExtraLarge.ShouldBe(24);

        UiSize.Radius.Small.ShouldBe(4);
        UiSize.Radius.Medium.ShouldBe(8);
        UiSize.Radius.Large.ShouldBe(12);
        UiSize.Radius.Pill.ShouldBe(999);

        UiSize.Stroke.Hair.ShouldBe(1);
        UiSize.Stroke.Signal.ShouldBe(2);
        UiSize.Stroke.Beam.ShouldBe(3);

        // Plain constants keep the fraction that a Godot theme constant would round away.
        UiSize.Stroke.Number.ShouldBe(1.5f);
    }

    [Fact]
    public void LayoutDimensions_MatchTheReferenceShell()
    {
        UiLayout.CanvasWidth.ShouldBe(640);
        UiLayout.CanvasHeight.ShouldBe(360);
        UiLayout.TopBarHeight.ShouldBe(48);
        UiLayout.SidePanelWidth.ShouldBe(176);
        UiLayout.ColumnSmallWidth.ShouldBe(52);
        UiLayout.ColumnMediumWidth.ShouldBe(76);
        UiLayout.ColumnLargeWidth.ShouldBe(96);
    }

    [Fact]
    public void TextColorVariations_ChainEveryTypographyOntoEveryTextColor()
    {
        var variations = UiThemeExpander.TextColorVariations;

        variations.Count.ShouldBe(
            Enum.GetValues<UiTokens.Typography>().Length
            * Enum.GetValues<UiTokens.Color>().Count(UiTokens.IsTextColor));
        variations.Select(variation => variation.Name).ShouldBeUnique();
        variations.ShouldContain(new UiThemeExpander.ColorVariation("UiNoteMuted", "UiNote", UiTokens.Color.Muted));
        variations.ShouldContain(new UiThemeExpander.ColorVariation("UiLabelOnAccent", "UiLabel", UiTokens.Color.OnAccent));
    }

    [Fact]
    public void TextColorVariation_RejectsNonTextColors()
    {
        Should.Throw<ArgumentOutOfRangeException>(
            () => UiTokens.Variation(UiTokens.Typography.Body, UiTokens.Color.Panel));
    }

    [Fact]
    public void Uppercase_IsATypographyPropertyNotAPaletteValue()
    {
        Enum.GetValues<UiTokens.Typography>()
            .Where(UiTokens.IsUppercase)
            .ShouldBe(new[] { UiTokens.Typography.Stage, UiTokens.Typography.Label, UiTokens.Typography.Overline });
    }
}
